version: '3.8'
services:
  apache_server:
    container_name: symfony
    ports:
    - '800:80'
    image: ubuntu-php7.1
    volumes:
    - ./symfony:/var/www/html/symfony
    build: .

  mysql:
    container_name: base_de_datos
    ports:
      - '3300:3306'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: symfony
      MYSQL_USER: dbEvan
      MYSQL_PASSWORD: 123
